# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np;
np.zeros((100), int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [4]:
np.ones((100), int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [6]:
np.ones((100), int) * 3

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [11]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
m = matrix
m[1],m[2]=m[2],m[1].copy()
m

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

#### 6. Создать вектор со значениями от 10 до 100

In [12]:
np.arange(10,101)


array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [15]:
np.arange(10,101)
reversed_arr = np.arange(10,101)[::-1] #a[::-1]  all items in the array, reversed
print(reversed_arr)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [19]:
np.arange(16).reshape(4,4) # it`s not supposed to be 17 digits in 4x4 matrix.


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [25]:
arr = np.array([1,2,3,4,5])
arr0 = np.zeros((len(arr) + (len(arr)-1)*3),dtype=int)  #?
# каждый 4 элемент
arr0[::4] = arr
print(arr0)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [28]:
np.ones(9,(int)).reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [12]:
np.random.randint(0, 192002, (3,3,3))

array([[[ 26779,  95468,  27645],
        [ 67660,  94165, 160155],
        [ 46998, 128965,   3242]],

       [[160971,  49602,  24900],
        [123531,  33891,  82297],
        [172080, 170617, 145711]],

       [[ 30211, 188858, 100671],
        [112622,  65806,   9190],
        [108433, 163948, 156142]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [17]:
array = np.random.randint(-2000000, 2000000, (10,10))
print(array.min())
print(array.max())


-1944236
1987322


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [21]:
array = np.random.random(30)
print (array)
print(np.mean(array))


[0.76249202 0.3125887  0.07991159 0.53911034 0.75060768 0.71762224
 0.94187742 0.89198638 0.62395828 0.70940029 0.79839368 0.14916073
 0.25711363 0.30979431 0.67454661 0.63975511 0.31570288 0.50675858
 0.30616928 0.11389068 0.7107561  0.282482   0.61237221 0.49545533
 0.79770526 0.15384124 0.80510292 0.75116732 0.64317134 0.13547511]
0.5262789760478561


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [23]:
a = np.ones((5,5), int)
a[1:-1,1:-1] = 0 #
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [24]:
np.roots([1, 4, -2, 3])
#finds roots of equation x^3+4x^2-2x+3=0; j means that element is imaginary

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [31]:
a = np.diag([1,2,2,4], k=-1) 
#Parameters
#----------
#v : array_like
#    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
#    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
#    diagonal.
#k : int, optional
#    Diagonal in question. The default is 0. Use `k>0` for diagonals
#    above the main diagonal, and `k<0` for diagonals below the main
#    diagonal.
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [32]:
a = np.ones((8,8), dtype=int)
a[1::2,::2] = 0 #?
a[::2,1::2] = 0 #?
print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [34]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [35]:
np.tile(np.array([[1,0],[0,1]]),(4,4))


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [44]:
a = np.random.randint(5, size=(5,3))
b = np.random.randint(5, size=(3,2))
print(a)
print(b)
a.dot(b)

[[1 1 1]
 [3 1 0]
 [1 0 2]
 [2 3 0]
 [0 2 1]]
[[3 0]
 [1 4]
 [1 4]]


array([[ 5,  8],
       [10,  4],
       [ 5,  8],
       [ 9, 12],
       [ 3, 12]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [54]:
a = np.arange(10)
a[(3<a) & (a<8)] *= -1
print(a)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [55]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [56]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [59]:
np.linspace(0,1,11,dtype=float)[1:-1]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26. Отсортировать вектор

In [65]:
a = np.random.random(10)
print(a)
a.sort()
a

[0.70653621 0.99840589 0.41868437 0.20332918 0.3129613  0.3241465
 0.06616284 0.37206318 0.04388963 0.59304226]


array([0.04388963, 0.06616284, 0.20332918, 0.3129613 , 0.3241465 ,
       0.37206318, 0.41868437, 0.59304226, 0.70653621, 0.99840589])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [81]:
a = np.random.randint(0,2,3)
b = np.random.randint(0,2,3)
equal = np.allclose(a,b)
print(a)
print(b)
print(equal)
c = np.random.randint(0,3,2)
d = np.random.randint(0,3,2)
equal = np.allclose(c,d)
print(c)
print(d)
print(equal)
q = np.random.randint(0,2,2)
w = np.random.randint(0,2,2)
equal = np.allclose(q,w)
print(q)
print(w)
print(equal)
e = np.random.randint(0,2,2)
r = np.random.randint(0,2,2)
equal = np.allclose(e,r)
print(e)
print(r)
print(equal)



[1 0 1]
[1 0 1]
True
[2 2]
[2 2]
True
[1 0]
[1 1]
False
[1 0]
[0 0]
False


#### 28. Сделать массив неизменяемым

In [84]:
a = np.zeros(10)
a.flags.writeable = False
a[1] = 1
#assignment destination is read-only

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [85]:
arr = np.random.randint(0,10,20)
arr.sort()
n = 5
print(arr)
print(arr[-n:]) #

[0 1 1 2 3 3 3 4 5 7 8 8 8 8 9 9 9 9 9 9]
[9 9 9 9 9]


#### 30. Заменить максимальный элемент на ноль

In [87]:
arr = np.random.randint(0,30,5)
print(arr)
arr[arr==arr.max()]=0
print(arr)

[ 8  0 29 15  3]
[ 8  0  0 15  3]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [88]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(a)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [96]:
a = np.random.random(10)
b = np.random.random(10)
c = 1.0 / np.subtract.outer(a, b)
print(c)

[[ -3.16971111  -2.16008602  -2.98961004  -1.32411185  -1.32374366
  -14.18075936  -1.87791595  -2.32413093  -1.51123588   8.51202142]
 [  3.40247468   6.82848503   3.63771146  -6.85714378  -6.84728081
    1.85572892  13.00648932   5.58280165 -19.11308499   1.37576031]
 [ 15.72571419 -11.92346394  22.42932191  -2.65853561  -2.65705177
    3.24087973  -6.51767627 -19.53427244  -3.53814736   2.01386673]
 [ -7.8599512   -3.64052555  -6.83840761  -1.76377949  -1.76312625
    8.49323074  -2.904897    -4.13207009  -2.11215028   3.27075487]
 [-25.82681035  -5.3712092  -17.32349404  -2.09005417  -2.08913696
    4.84851718  -3.91024447  -6.514588    -2.59778477   2.53647697]
 [  3.36598092   6.68306895   3.59602803  -7.01032067  -7.00001247
    1.84482003  12.48888729   5.48522215 -20.35263352   1.36975552]
 [ -2.61666378  -1.88813057  -2.49269859  -1.21668848  -1.2163776
   -7.28873876  -1.66893347  -2.01228208  -1.37289102  19.68463445]
 [ -7.16105948  -3.48307656  -6.30319255  -1.72597942  -

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [97]:

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [103]:
# set_printoptions - Параметры вывода
# threshold - Задает общее количество элементов массива, превышение которого запускает механизм сокращенного вывода
np.set_printoptions(threshold=np.inf) #inf not inifinity
a = np.ones((10,10), int)
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [105]:
a = 10*np.random.random(10)
x = 5
print(a)
index = (np.abs(a-x)).argmin()
print(a[index])

[3.26545751 9.16165294 1.89300868 5.06558815 8.68114315 6.03718582
 9.99545243 4.15868449 3.55324062 8.83954237]
5.065588151493942


#### 36. Преобразовать массив из float в int

In [113]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy = False) #astype ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)¶
# Copy of the array, cast to a specified type
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [114]:
a = np.arange(27).reshape(3,3,3)
print(a)
for index, value in np.ndenumerate(a):
    print(index, value)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(0, 2, 0) 6
(0, 2, 1) 7
(0, 2, 2) 8
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 1, 0) 12
(1, 1, 1) 13
(1, 1, 2) 14
(1, 2, 0) 15
(1, 2, 1) 16
(1, 2, 2) 17
(2, 0, 0) 18
(2, 0, 1) 19
(2, 0, 2) 20
(2, 1, 0) 21
(2, 1, 1) 22
(2, 1, 2) 23
(2, 2, 0) 24
(2, 2, 1) 25
(2, 2, 2) 26


#### 38. Случайно расположить p элементов в 2D массив

In [119]:
n = 10
p = 33
a = np.zeros((n,n), int)
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
print(a)

[[0 0 0 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 1 0 1 0]
 [0 1 0 1 1 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 1 0]
 [0 0 1 0 1 0 1 0 1 1]
 [0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 1 1 0 1 1 1 0 0]
 [0 0 1 1 0 1 1 0 1 0]
 [0 0 0 1 1 0 0 0 0 0]]


#### 39. Отнять среднее из каждой строки в матрице

In [126]:
a = np.random.randint(0,10,(2,5))
print(a)
# axis 0 - столбцы, 1-строки
b = a - a.mean(axis=1, keepdims=True)
print(b)
print(a.mean(axis=1, keepdims=True))

[[6 9 8 8 8]
 [6 3 5 6 0]]
[[-1.8  1.2  0.2  0.2  0.2]
 [ 2.  -1.   1.   2.  -4. ]]
[[7.8]
 [4. ]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [131]:
a = np.random.randint(0,10,(5,5))
n = 1  # Нумерация с нуля
print(a)
# a[:,n] - n-ый столбик
# argsort() - возвращает список индексов отсортированный по элементам
print(a[a[:,n].argsort()])

[[8 9 5 8 7]
 [0 8 3 1 9]
 [7 8 1 1 6]
 [6 2 1 0 3]
 [2 4 7 6 7]]
[[6 2 1 0 3]
 [2 4 7 6 7]
 [0 8 3 1 9]
 [7 8 1 1 6]
 [8 9 5 8 7]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [145]:
a = np.random.randint(0,2,(3,3))
print(a)
print((~a.any(axis=0)).any())

[[1 1 0]
 [1 1 0]
 [1 0 0]]
True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [149]:
#?
a = np.ones(10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 6 6 4 6 3 1 8 5 1 1 8 1 8 0 3 0 2 9 2]
[3. 5. 3. 3. 3. 2. 4. 1. 4. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
#?picture?

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [154]:
a = np.random.randint(0,10, (2,2,2,2))
print(a)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[8 8]
   [5 5]]

  [[9 2]
   [4 7]]]


 [[[5 6]
   [9 9]]

  [[5 8]
   [7 2]]]]
[[100  79  58  75]
 [ 70  70  82  64]
 [ 77  80  88  72]
 [ 50  69  79  75]]
