In [2]:
import numpy as np

## 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
> а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)

In [6]:
A = np.random.randint(1,10,(4,2))
B = np.random.randint(1,10,(4,2))
A, B

(array([[3, 3],
        [9, 3],
        [4, 6],
        [4, 5]]), array([[8, 1],
        [8, 6],
        [5, 1],
        [5, 6]]))

In [7]:
np.dot(A,B)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [9]:
np.dot(B,A)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

> б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$

In [11]:
A = np.random.randint(1,10,(2,5))
B = np.random.randint(1,10,(5,3))
A, B

(array([[3, 9, 4, 5, 2],
        [2, 3, 6, 5, 3]]), array([[1, 4, 3],
        [6, 3, 5],
        [3, 2, 6],
        [2, 1, 6],
        [8, 7, 7]]))

In [13]:
C = np.dot(A,B)
C.shape

(2, 3)

In [14]:
np.dot(B,A)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

> в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$

In [15]:
A = np.random.randint(1,10,(8,3))
B = np.random.randint(1,10,(3,8))
A, B

(array([[4, 7, 3],
        [5, 4, 5],
        [8, 2, 9],
        [8, 8, 5],
        [3, 8, 6],
        [3, 2, 2],
        [9, 9, 7],
        [6, 1, 8]]), array([[2, 9, 2, 7, 3, 4, 7, 2],
        [2, 6, 4, 3, 5, 9, 5, 8],
        [6, 7, 7, 4, 1, 3, 4, 1]]))

In [17]:
C = A @ B
C, C.shape

(array([[ 40,  99,  57,  61,  50,  88,  75,  67],
        [ 48, 104,  61,  67,  40,  71,  75,  47],
        [ 74, 147,  87,  98,  43,  77, 102,  41],
        [ 62, 155,  83, 100,  69, 119, 116,  85],
        [ 58, 117,  80,  69,  55, 102,  85,  76],
        [ 22,  53,  28,  35,  21,  36,  39,  24],
        [ 78, 184, 103, 118,  79, 138, 136,  97],
        [ 62, 116,  72,  77,  31,  57,  79,  28]]), (8, 8))

In [19]:
C = B @ A
C, C.shape

(array([[221, 207, 195],
        [229, 181, 234],
        [201, 167, 184]]), (3, 3))

> г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [20]:
A = np.random.randint(1,10,(4,4))
B = np.random.randint(1,10,(4,4))
A, B

(array([[3, 7, 2, 4],
        [4, 6, 6, 7],
        [9, 3, 5, 7],
        [4, 9, 7, 9]]), array([[7, 1, 1, 7],
        [2, 9, 7, 9],
        [1, 9, 4, 6],
        [2, 1, 5, 6]]))

In [21]:
C = A @ B
C, C.shape

(array([[ 45,  88,  80, 120],
        [ 60, 119, 105, 160],
        [ 88,  88,  85, 162],
        [ 71, 157, 140, 205]]), (4, 4))

In [22]:
C = B @ A
C, C.shape

(array([[ 62, 121,  74, 105],
        [141, 170, 156, 201],
        [ 99, 127, 118, 149],
        [ 79,  89,  77, 104]]), (4, 4))

## 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [23]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0,5]])

In [24]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [25]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

## 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [26]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [27]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

## 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

In [28]:
A = np.array([[4,1], [5, -2], [2, 3]])

In [29]:
A@A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [30]:
A.T@A

array([[45,  0],
       [ 0, 14]])

## 5. Вычислить определитель:

a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^2x+cos^2x=1$$

In [31]:
A = np.array([[0, -1], [1, 0]])
np.linalg.det(A)

1.0

б)

$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [32]:
A = np.array([[4,2,3],[0,5,1],[0,0,9]])
np.linalg.det(A)

180.0

в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(A))

-0.0

## 6. Доказать, что матрица$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$вырожденная.

In [35]:
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(A)

0.0

Так как определитель матрицы равен 0, то матрица вырожденная.

## 7. Найти ранг матрицы а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [40]:
A = np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(A)

2